### PR TITLE
Update autotask dependecies versions

### PR DESCRIPTION
**Pull request by zeljkoX**
This PR will update autotask dependencies versions to match latest ones that are going to be pushed within the next release.

### CODE REVIEW

**Review by spalladino — COMMENTED** [review]
Heads up we also include the resulting lockfile whenever we change deps!

**Comment by zeljkoX** [comment]
> Heads up we also include the resulting lockfile whenever we change deps!

This is just documentation change. 
lockfile is included [here](https://github.com/OpenZeppelin/defender/pull/2846)
Am I missing something?

**Comment by spalladino** [comment]
See [here](https://github.com/OpenZeppelin/defender-docs/blob/main/docs/modules/ROOT/attachments/yarn.lock)! We also include it here in the docsite so a dev that wants to reproduce the exact same environment locally can download this file.

**Comment by zeljkoX** [comment]
> See [here](https://github.com/OpenZeppelin/defender-docs/blob/main/docs/modules/ROOT/attachments/yarn.lock)! We also include it here in the docsite so a dev that wants to reproduce the exact same environment locally can download this file.

Thanks for reference. 
I'll add note to deploy document so we don't miss this in the future.
Seems like that latest lock file includes version clients libararies version `1.10.0`.

**Pull request merged**
