### PR TITLE
Update gas price oracles used

### PR DESCRIPTION
**Pull request by spalladino**

### CODE REVIEW

**Review by abcoathup — APPROVED** [review]
LGTM

What oracles are used for xDAI and Fuse?

**Comment by spalladino** [comment]
> What oracles are used for xDAI and Fuse?

Gas prices are hardcoded for those.

**Comment by spalladino** [comment]
And thanks for the review Andy!!

**Comment by abcoathup** [comment]
> Gas prices are hardcoded for those.

We could add a line that 
xDAI and Fuse gas prices are fixed.

**Comment by spalladino** [comment]
Well, xDAI itself already publishes that their gas price is fixed (see [here](https://www.xdaichain.com/for-developers/developer-resources#general-information)), and Fuse does the same. I think that most devs who build on those chains don't worry about gas prices, so no need to include that info here.

Let's do something: first time a user asks for it, we'll include it.

**Pull request merged**
